Init models api
awesome-academy/Daily-Weather pull request #3
Opened 2020-08-19 03:18 UTC by ken2798

## Related Tickets
#26724

## What's this PR do ?

- Create models Api from: https://openweathermap.org/api

## Notes
*(Other notes)*

2020-08-20 01:27 UTC, datdt-1935 requested changes
Sử dụng đúng mô hình MVC theo mẫu như này:
https://github.com/daolq3012/Structure_IOS/tree/mvc_architect

2020-08-20 01:27 UTC, datdt-1935 commented on Daily-Weather/Controller/HomeViewController.swift
> +class HomeViewController: UIViewController, UITableViewDelegate, UITableViewDataSource, CLLocationManagerDelegate {
nên tách ra các extension cho rõ ràng

2020-08-20 01:27 UTC, datdt-1935 commented on Daily-Weather/Controller/HomeViewController.swift
> +
xoá dòng trắng

2020-08-20 01:27 UTC, datdt-1935 commented on Daily-Weather/Controller/HomeViewController.swift
> +    @IBOutlet var table: UITableView!
```suggestion
    @IBOutlet private weak var tableView: UITableView!
```

2020-08-20 01:27 UTC, datdt-1935 commented on Daily-Weather/Controller/HomeViewController.swift
> +
xoá dòng trắng

2020-08-20 01:27 UTC, datdt-1935 commented on Daily-Weather/Controller/HomeViewController.swift
> +        locationManager = CLLocationManager()
ở trên khởi tạo rồi ở đây lại khởi tạo lại làm gì em nhỉ?

2020-08-20 01:27 UTC, datdt-1935 commented on Daily-Weather/Controller/HomeViewController.swift
> +    func requestWeatherForLocation(){
```suggestion
    func requestWeatherForLocation() {
```

2020-08-20 01:27 UTC, datdt-1935 commented on Daily-Weather/Controller/HomeViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: TableViewCell.identifier, for: indexPath) as! TableViewCell
không force unwrap

2020-08-20 01:27 UTC, datdt-1935 commented on Daily-Weather/Controller/HomeViewController.swift
> +        return 2
để ra constant

2020-08-20 01:27 UTC, datdt-1935 commented on Daily-Weather/Scenes/MainScreen/TableViewCell/TableViewCell.swift
> +class TableViewCell: UITableViewCell {
nên để rõ tên là TableViewCell của cái gì

2020-08-28 02:36 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/CoordinateData.swift
> +final class CoordinateData {
dùng struct đi em

2020-08-28 02:36 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/CoordinateData.swift
> +    static var coor = CoordinateData()
biến này để làm gì nhỉ?

2020-08-28 02:36 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/CoordinateData.swift
> +        let currentLocation: CLLocationCoordinate2D = locationManager.location!.coordinate
không force unwrap

2020-08-28 02:36 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/LocationData.swift
> +            {(placemarks, error) in
```suggestion
        ceo.reverseGeocodeLocation(loc) { (placemarks, error) in
```

2020-08-28 02:36 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/LocationData.swift
> +                }
xem lại coding convention

2020-08-28 02:36 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/LocationData.swift
> +                let pm = placemarks! as [CLPlacemark]
không force unwrap

2020-08-28 02:36 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/LocationData.swift
> +        var addressString : String = ""
```suggestion
        var addressString = ""
```

2020-08-28 02:36 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/LocationData.swift
> +                    }
tương tự

2020-08-28 02:36 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/WeatherData.swift
> +            let url = "https://api.openweathermap.org/data/2.5/onecall?lat=\(lat)&lon=\(lon)&%20exclude=daily&appid=051eccdec971db6541e789fd524cfb66"
để ra 1 file Urls riêng

2020-08-28 02:36 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/WeatherData.swift
> +            URLSession.shared.dataTask(with: URL(string: url)!, completionHandler: {
```suggestion
            URLSession.shared.dataTask(with: URL(string: url)!) {
```
Không force unwrap

2020-08-28 02:44 UTC, ken2798 commented on Daily-Weather/Services/Remote/CoordinateData.swift
> +    static var coor = CoordinateData()
dạ e khởi tạo để trong ViewController gọi đến ễtntion update ạ

2020-08-28 09:42 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/APIUrl.swift
> +    static let baseUrl = "https://api.openweathermap.org/data/2.5/onecall?lat=\(CoordinateData.coor.lat)&lon=\(CoordinateData.coor.lon)&%20exclude=daily&appid=051eccdec971db6541e789fd524cfb66"
dùng String.format để thêm tham số chứ không để dạng static như này

2020-08-28 09:42 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/CoordinateData.swift
> +    static var coor = CoordinateData()
vậy thì không cần phải để static đâu. Và ViewController khởi tạo cũng được

2020-08-28 09:42 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/LocationData.swift
> +                    }
gộp tất cả chỗ này vào 1 if-let thôi em

2020-08-28 09:42 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/WeatherData.swift
> +    public func fetchCoursesJSON( with lon : CLLocationDegrees, lat : CLLocationDegrees, completion: @escaping (Result<DataWeather, Error>) -> ()) {
break line và format lại code nhé

2020-08-28 09:42 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/WeatherData.swift
> +                    data, response, error in
để 1 dòng thôi em

2020-08-28 09:42 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/WeatherData.swift
> +                    data, response, error in
để 1 dòng thôi em

2020-08-28 09:42 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/LocationData.swift
> +                    }
gộp tất cả chỗ này vào 1 if-let thôi em

2020-08-28 09:42 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/WeatherData.swift
> +                    }
guard data và error để completion ra chứ không force unwrap

2020-08-28 09:42 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/WeatherData.swift
> +                        completion(.success(json!))
tương tự

2020-08-28 09:42 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/WeatherData.swift
> +                    }.resume()
format code

2020-09-08 01:53 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/APIUrl.swift
> +        url = url + "/onecall?lat=\(String(lat))&lon=\(String(lon))&%20exclude=daily&appid=051eccdec971db6541e789fd524cfb66"
```suggestion
        let url = baseUrl + "/onecall?lat=\(String(lat))&lon=\(String(lon))&%20exclude=daily&appid=051eccdec971db6541e789fd524cfb66"
```
để key sang 1 file riêng và ignore file đó đi em. Không đẩy key lên github

2020-09-08 01:53 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/APIUrl.swift
> +    static var api = APIUrl()
```suggestion
    static let instance = APIUrl()
```

2020-09-08 01:53 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/LocationData.swift
> +                let pm = placemarks![0]
không force unwrap

2020-09-08 01:53 UTC, datdt-1935 commented on Daily-Weather/Services/Remote/LocationData.swift
> +                if let subLocalityy = pm.subLocality, let thoroughfacree = pm.thoroughfare, let localityy = pm.locality , let countryy = pm.country , let postalCodee = pm.postalCode {
break line ra em

2020-09-08 03:42 UTC, datdt-1935 approved these changes

2020-09-08 03:42 UTC, merged